### PR TITLE
fix: input field button is always inside input field

### LINKED ISSUE #398: Max Button Should Be Inside Input On Mobile
In normal desktop mode, the "Max" button on the send screen appears inside the Amount input:

Screen Shot 2022-10-04 at 2 34 48 PM

However in the mobile layout, it appears as a separate button outside the input:

Screen Shot 2022-10-04 at 2 34 42 PM

I think the Max button should remain inside the input even in mobile mode. It's a small button and should be easy enough to tap even in a smaller context. Having a it as a separate button could create some UX confusion between "Max" and "Send".

### PR DESCRIPTION
**Pull request by mds1**
Closes #398

### CODE REVIEW

File: frontend/src/components/BaseInput.vue [hunk 1]
```diff
@@ -120,12 +90,6 @@ export default defineComponent({
       default: undefined,
     },
 
-    counter: {
```
Comment (mds1) [inline frontend/src/components/BaseInput.vue:123]: This `counter` prop was used way back when we only generated a 16 byte random number and allowed a 16 byte memo. The counter was used to show how much more text you can fit in the memo. Since that was removed because it reduced security a lot, we no longer use this `counter` prop anywhere, so I deleted it

**Review by garyghayrat — APPROVED** [review]
lgtm!

**Review by apbendi — APPROVED** [review]
Looks good and works well!
