### PR TITLE
Fix overlapping messages

### LINKED ISSUE #525: Negative margins are causing formatting issues
When directly copying in an ENS with confusables or directly copying an ENS name that is not supported the negative makes the error message difficult to read. It is probably a race condition.

image

_Originally posted by @mds1 in https://github.com/ScopeLift/umbra-protocol/pull/523#discussion_r1211999580_

### PR DESCRIPTION
**Pull request by alexkeating**
### Description

- There is a gap, but there shouldn't be overlapping messages.

[Screencast from 2023-06-22 13-01-51.webm](https://github.com/ScopeLift/umbra-protocol/assets/12705146/64506a78-3981-4cdc-b5d3-fa30250fc65d)

Closes #525

### CODE REVIEW

**Review by garyghayrat — APPROVED** [review]
lgtm! Seems like only 'm' from the alphabet is considered a confusable character?

File: frontend/src/pages/AccountSend.vue [hunk 1]
```diff
@@ -115,25 +115,16 @@
...
 
           <!-- Identifier, advanced mode tooltip -->
-          <div
-            v-if="advancedMode"
-            class="row items-center text-caption q-pt-sm q-pb-lg"
-            :style="
-              !recipientId || isValidRecipientId || (!isValidRecipientId && recipientIdWarning) ? 'margin-top:-2em' : ''
-            "
-          >
+          <div v-if="advancedMode" class="row items-center text-caption q-pt-sm">
```
Comment (alexkeating) [inline frontend/src/pages/AccountSend.vue:127]: (arbitrary thread)

@garyghayrat Yes, it seems like some ascii characters are marked as confusable. m is considered confusable because it is close to rn. I think it is overly strict and it may make sense to create an issue to relax. @mds1 Any thoughts on this?

Comment (mds1) [reply frontend/src/pages/AccountSend.vue:127]: Hmm my initial reaction is to agree it's overly strict for our use case. Does ENS or ensjs have guidance for apps on how they recommend handling this? Wonder what most popular apps do here

Comment (alexkeating) [reply frontend/src/pages/AccountSend.vue:127]: ENS and ensjs handle detecting confusables in the normalization process. They have an esip and library we could use, but it is heavier than only detecting confusables.

https://docs.ens.domains/ens-improvement-proposals/ensip-15-normalization-standard#wholes

https://github.com/adraffy/ens-normalize.js/tree/main

**Review by apbendi — APPROVED** [review]
LGTM thanks for resolving this!
