### PR TITLE
On receive page, ask user to setup account if unregistered

### LINKED ISSUE #569: Use isAccountSetup from walletStore to prevent unnecessary fetching and scanning
Fix the regression caused by https://github.com/ScopeLift/umbra-protocol/pull/568 . 
After merging the PR, filtering announcements will no longer return an empty `userAnnouncements` array when the `startBlock` is undefined(i.e. user registered block couldn't be found, undefined). Instead it reverts back to `chainConfig` default `startblock`.

Idea to fix: check `isAccountSetup` on the receive page before requiring user signature and a scan, and prompt the user to set up their account if they are not in advanced mode.

### PR DESCRIPTION
**Pull request by garyghayrat**
Closes #569 

Before:

https://github.com/ScopeLift/umbra-protocol/assets/61768337/81ead8bf-39c3-490c-94ab-2fde789a0bc8

After: 

https://github.com/ScopeLift/umbra-protocol/assets/61768337/38d2f130-528b-45ab-bb42-39ddfeb6dea8

### CODE REVIEW

File: frontend/src/pages/AccountReceive.vue [hunk 1]
```diff
@@ -11,7 +11,19 @@
       </div>
     </div>
 
-    <div v-else class="q-mx-auto" style="max-width: 800px">
+    <div
+      v-else-if="!isAccountSetup && !advancedMode"
+      class="dark-toggle text-center text-bold q-pa-md q-mb-lg"
+      style="border-radius: 15px"
+      :style="isDark ? 'color: #FFFAEB; background-color: #7C5E10' : 'color: #513C06; background-color: #FCEFC7'"
```
Comment (alexkeating) [inline frontend/src/pages/AccountReceive.vue:18]: It is better to use one of the quasar shading classes or the sass variables we have setup in the app. It allows us to keep the colors consistent in the app.

**Review by alexkeating — COMMENTED** [review]
Working for me one small comment

File: frontend/src/pages/AccountReceive.vue [hunk 2]
```diff
@@ -11,7 +11,19 @@
       </div>
     </div>
 
-    <div v-else class="q-mx-auto" style="max-width: 800px">
+    <div
+      v-else-if="!isAccountSetup && !advancedMode"
+      class="dark-toggle text-center text-bold q-pa-md q-mb-lg"
```
Comment (mds1) [inline frontend/src/pages/AccountReceive.vue:16]: IMO we should keep the max-width, it looks odd to have the message take the full width of the page

image

File: frontend/src/pages/AccountReceive.vue (hunk 1 above)
Comment (mds1) [reply frontend/src/pages/AccountReceive.vue:18]: Yea try to avoid `style` as much as possible for the reason @alexkeating mentioned. I believe quasar has classes for border radius, maybe max width also

Comment (garyghayrat) [reply frontend/src/pages/AccountReceive.vue]: Good to know, thank you! Addressed it in https://github.com/ScopeLift/umbra-protocol/pull/571/commits/d34d75c3e854848b58237035fb4eea4868304fdc
- Quasar Palette didn't really have colors that were close so created custom text and bg colors in sass file
- Quasar rounded border class wasn't round enough so also created a custom class in sass
- Quasar max-width option didn't match our widths, so just reused an existing sass class.

File: frontend/src/pages/AccountReceive.vue (hunk 2 above)
Comment (garyghayrat) [reply frontend/src/pages/AccountReceive.vue]: Addressed it in https://github.com/ScopeLift/umbra-protocol/commit/d34d75c3e854848b58237035fb4eea4868304fdc

File: frontend/src/pages/AccountReceive.vue (hunk 1 above)
Comment (garyghayrat) [reply frontend/src/pages/AccountReceive.vue]: Ran prettier on .sass https://github.com/ScopeLift/umbra-protocol/pull/571/commits/cdbf1a522403bc910a36c40d0bf0b750e7e392ea

Comment (mds1) [reply frontend/src/pages/AccountReceive.vue]: Thanks! Since you pulled things out into classes, should we also pull out existing hardcoded classes, e.g. the `:style="isDark ? 'color: #FFFAEB; background-color: #7C5E10' : 'color: #513C06; background-color: #FCEFC7'"` line in this PR? Or a follow up PR?

Comment (garyghayrat) [reply frontend/src/pages/AccountReceive.vue]: There seems to be a lot more of those. Let me create an issue for it and fix them in a separate PR

Comment (garyghayrat) [reply frontend/src/pages/AccountReceive.vue]: Created an issue https://github.com/ScopeLift/umbra-protocol/issues/572

**Review by alexkeating — APPROVED** [review]

File: frontend/src/css/app.sass [hunk 3]
```diff
@@ -76,8 +76,6 @@
 .danger
```
Comment (apbendi) [inline frontend/src/css/app.sass:76]: *arbitrary comment location*

Hey @garyghayrat, overall this is looking good, however I'm observing the following behavior with regards to advanced mode: if the user has never registered stealth keys before, but turns on advanced mode, it now fetches and scans *all announcements*. Why is this the case? We should only need to scan all blocks if the user supplies a private key (because now we don't know when that was registered) or if the user specifies a block range (in which case we should respect it). Am I missing something?

**Review by apbendi — COMMENTED** [review]
Looking good @garyghayrat, but a question about advanced mode behavior.

File: frontend/src/css/app.sass (hunk 3 above)
Comment (garyghayrat) [reply frontend/src/css/app.sass:76]: Updated here: https://github.com/ScopeLift/umbra-protocol/pull/571/commits/ac938e6ec365de35ee3c76035eb169357c5a601a

Comment (apbendi) [reply frontend/src/css/app.sass:76]: Ok @garyghayrat, now I'm seeing the opposite problem:

* I connect with an account that *has* completed setup, and *does* have past transactions in its history
* I turn on advanced mode and scan
* It completes immediately and it shows no transactions
* I turn advanced mode off, refresh and scan
* It scans much longer and shows the past transactions

See the video below:

umbra-advanced-no-scan

Comment (garyghayrat) [reply frontend/src/css/app.sass:76]: Ok, this should fix it: https://github.com/ScopeLift/umbra-protocol/pull/571/commits/dd8e70078af457c73b67a3589e92e25df5510809

**Review by apbendi — APPROVED** [review]
Seems to be working well @garyghayrat, thanks!
