### PR TITLE
Remove unsorted state

### LINKED ISSUE #540: Sorting Behavior on the Receive Table is Broken & Unpredictable
On the Receive table, when you try to sort by clicking on any given column, there are broken results:

* Sometimes the click seems to have no effect on either the order or the arrow
* Sometime the click changes the order but not the arrow
* Sometimes the click changes the arrow but not the order
* Clicking the same column multiple times will cycle through multiple states, none or some of which reprsent proper sort order

sorting-receive

### PR DESCRIPTION
**Pull request by alexkeating**
#### Description

- Sort order does not become confused when the unsorted state is removed

Closes #540

### CODE REVIEW

File: frontend/src/components/AccountReceiveTable.vue [hunk 1]
```diff
@@ -78,6 +78,7 @@
         card-container-class="col q-col-gutter-md"
         :columns="mainTableColumns"
         :rows="formattedAnnouncements"
+        :binary-state-sort="true"
```
Comment (alexkeating) [inline frontend/src/components/AccountReceiveTable.vue:81]: This fixed the issue locally for me, but my test sorts are pretty basic.

File: frontend/src/components/AccountReceiveTable.vue [hunk 2]
```diff
@@ -78,6 +78,7 @@
         card-container-class="col q-col-gutter-md"
         :columns="mainTableColumns"
```
Comment (garyghayrat) [inline frontend/src/components/AccountReceiveTable.vue:79]: *random placement for comment*

I'm seeing this weird behavior both on firefox and brave
Screen Shot 2023-06-20 at 1 08 02 PM

**Review by garyghayrat — APPROVED** [review]
lgtm!

**Review by mds1 — APPROVED** [review]

**Review by apbendi — APPROVED** [review]
Added https://github.com/ScopeLift/umbra-protocol/issues/550 to track amount based sorting improvements. Otherwise LGTM!
