### PR TITLE
Make isAddress more async

### LINKED ISSUE #373: Use asynchronous Promise when checking address input
Use [`Promise.allSettled`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled) so failed promises can be handled within `isAddressSafe` instead of having the caller handle it.

Reference link: https://github.com/ScopeLift/umbra-protocol/pull/371#discussion_r940266355

### PR DESCRIPTION
**Pull request by alexkeating**
#### Description

- Make isAddress more async, and handle errors in isAddress

Closes #373

### CODE REVIEW

File: frontend/src/utils/address.ts [hunk 1]
```diff
@@ -116,21 +122,35 @@ export const isAddressSafe = async (name: string, userAddress: string, stealthAd
   if (destinationAddress.toLowerCase() === stealthAddress.toLowerCase()) reasons.push(`${tc('Utils.Address.it')} ${isDomain ? tc('Utils.Address.resolves-to') : tc('Utils.Address.is')} ${tc('Utils.Address.same-addr-as-stealth')}`); // prettier-ignore
 
   // Check if address owns any POAPs
-  if (await hasPOAPs(destinationAddress)) reasons.push(`${isDomain ? tc('Utils.Address.address-it-resolves-to') : tc('Utils.Address.it')} ${tc('Utils.Address.has-poap-tokens')}`); // prettier-ignore
+  const hasPOAPsCheck = async () => {
+    const has = await hasPOAPs(destinationAddress);
```
Comment (alexkeating) [inline frontend/src/utils/address.ts:126]: FYI: This was erroring locally. I think the domain changed.

https://documentation.poap.tech/reference/getactionsscan-5

Comment (mds1) [reply frontend/src/utils/address.ts:126]: Thanks for catching that, tracking in https://github.com/ScopeLift/umbra-protocol/issues/467

**Review by garyghayrat — APPROVED** [review]
lgtm!
