### PR TITLE
Use em instead of rem for icon size

### LINKED ISSUE #584: Remove repetitive console warnings
On the receive page, once signed, there are repetitive console warnings like: 
`Unexpected value 4rem parsing height attribute.` 
`Unexpected value 1rem parsing width attribute.`
`Unexpected value 1rem parsing height attribute.`

Most likely from the loading icons that were added to the account receive table component.

### PR DESCRIPTION
**Pull request by garyghayrat**
closes #584

### CODE REVIEW

File: frontend/src/components/AccountReceiveTable.vue [hunk 1]
```diff
@@ -100,7 +100,7 @@
                         ? formatNameOrAddress(props.row.formattedFrom)
                         : formatNameOrAddress(props.row.from)
                     }}</span>
-                    <loading-spinner v-if="!props.row.formattedFrom" size="1rem" customClass="q-ml-sm" />
+                    <loading-spinner v-if="!props.row.formattedFrom" size="16px" customClass="q-ml-sm" />
```
Comment (mds1) [inline frontend/src/components/AccountReceiveTable.vue:103]: Hm do you know why rem was a problem? It seems odd because the quasar docs [say](https://quasar.dev/vue-components/spinners) that rem is supported. Rem is nicer than px because px is absolute and rem is relative, so if the user changes the browser font size, rem units scale accordingly but pixel units don't

Comment (garyghayrat) [reply frontend/src/components/AccountReceiveTable.vue:103]: Ahh didn't realize rem had those benefits. Did some testings, those warnings are only showing up when using Firefox. Chromium-based browsers seem to be fine with rem.

Comment (garyghayrat) [reply frontend/src/components/AccountReceiveTable.vue:103]: Using `em` gets rid of those errors. Should I use that instead or close this PR entirely.

Comment (mds1) [reply frontend/src/components/AccountReceiveTable.vue:103]: Are things not rendering correctly in firefox because of the rem unit, or do they render correctly and we just want to get rid of the warning? 

Either way, em and rem are both relative so using em is just as good. But they are relative to a different base, so you might need to change the values (or not, if both bases are the same value)

Comment (garyghayrat) [reply frontend/src/components/AccountReceiveTable.vue:103]: they are rendering correctly but wanted to get rid of the warnings.

Comment (garyghayrat) [reply frontend/src/components/AccountReceiveTable.vue]: Updated to use em here: https://github.com/ScopeLift/umbra-protocol/pull/592/commits/8cd7ef181f8438eb2ab20a9afc5fc05bf927479d

Comment (alexkeating) [reply frontend/src/components/AccountReceiveTable.vue]: This might be what is going on here. Although, I am surprised Firefox doesn't support SVG 2 yet

https://stackoverflow.com/questions/46336500/svg-text-layout-rendering-differently-in-chrome-firefox-edge/46337386#46337386

**Review by alexkeating — APPROVED** [review]

**Review by mds1 — APPROVED** [review]
